finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('imageupload.urls')),
]

imageupload/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.home,name='home'),
]

imageupload/models.py
from django.db import models

class image(models.Model):
    photo = models.ImageField(upload_to="images")

imageupload/forms.py
from django import forms
from .models import image


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = image
        fields ='__all__'

imageupload/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import ImageUploadForm
from PIL import Image 

import numpy as np
import cv2, base64, re, os, subprocess


@csrf_exempt
def home(request):
	# if request.method == 'POST':
	# 	image = request.POST['image']
	# 	print('image received')
	# return render(request, 'home.html')

	

	if request.method == 'POST':
		form = ImageUploadForm(request.POST, request.FILES)
		if form.is_valid():
			img = request.FILES['photo']

			with open('./test.png', 'wb+') as f:
				for chunk in img.chunks():
					f.write(chunk)
			# im1 = Image.open(request.FILES['photo'])
			# im1.save('./test.png')
			img = cv2.imread('./test.png') # Read in the image and convert to grayscale
			#0 img = np.array(im1) # Read in the image and convert to grayscale
			gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
			gray = 255*(gray < 100).astype(np.uint8) # To invert the text to white
			coords = cv2.findNonZero(gray) # Find all non-zero points (text)
			x, y, w, h = cv2.boundingRect(coords) # Find minimum spanning bounding box
			rect = img[y:y+h, x:x+w] # Crop the image - note we do this on the original image
			# rect = cv2.rotate(rect, cv2.cv2.ROTATE_90_CLOCKWISE)
			# cv2.imshow("Cropped", rect) # Show it
			# cv2.waitKey(0)
			# cv2.destroyAllWindows()
			cv2.imwrite('./SimpleHTR-master/data/test.png', rect)

			# rect.save('./SimpleHTR-master/data/test.png')
			# im1.save('./test.png')
			os.chdir('./SimpleHTR-master/src')
			proc = subprocess.Popen(["python", "main.py"], stdout=subprocess.PIPE, shell=False)
	
			(out, err) = proc.communicate()
			print('here')
			os.chdir('../../')
			print('here')

			output = str(out)
			message = output[output.index('Recog'):].strip()
			recognized = ""
			for i in range(message.index('"')+1, 100):
				if message[i] == '"':
					break
				recognized += message[i]
			probability = message[message.index('0'):-5]
			
			img = form.save()
			ctx = {}
			ctx['recognized'] = recognized
			ctx['probability'] = probability
			with open('./SimpleHTR-master/data/test.png', "rb") as image_file:
				image_data = base64.b64encode(image_file.read()).decode('utf-8')
			ctx["image"] = image_data
			ctx["error"] = False
			return JsonResponse(ctx)

		else:
		   return JsonResponse({'error': True, 'errors': form.errors})
	else:
		form = ImageUploadForm()
		return render(request, 'home.html', {'form': form})

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Project</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
    <style>
        .loader {
          border: 16px solid #f3f3f3;
          border-radius: 50%;
          border-top: 16px solid #3498db;
          width: 120px;
          margin:30%;
          height: 120px;
          margin-top:70%;
          animation: spin 2s linear infinite;
        }
        .transparen {
            height: 100%;
            width: 100%;
            position:fixed;
            display: none;
            background-color: rgba(12,12,12,0.7);
        }
        
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
        </style>
</head>
<body>
    <div id="cover" class="transparen"> <div class="loader"></div></div>
    
   
    
	<div class="card-panel teal lighten-2 white-text" style="font-size:20px;"> Welcome to Character Recognition Program.</div>
	
	<div class="card-panel blue lighten-2" style="font-size:20px;"> Scan your writing from below.</div>
	<div class="container">
    <form 
    enctype="multipart/form-data"
    id="myform" method="POST"
    novalidate="">
      {% csrf_token %}
      
   	<div class="file-field input-field">
      <div class="btn">
        <span>File</span>
     
        <input type="file" name="photo" accept="image/*" required="" id="id_photo">
      </div>
      <div class="file-path-wrapper">
      
        <input class="file-path validate" type="text">
      </div>
    </div>
      <input type="submit" class="waves-effect waves-light btn" />
   </form>
   <br><br><br><br><br>
   <img id="image" style="width: 100%; height: 30%; max-height: 300px;">
   <div id="resultpart" style="font-size:22px;font-weight:700;">
   <p id="result"> <span id="recognized"></span> <br>
       <span id="probability"></span>
      </div>
<br>
</p>
</div>
</body>
 
<script>
 $('#myform').submit(function(e){
        e.preventDefault();
        $('#cover').css('display', 'block');
        $form = $(this)
        var formData = new FormData(this);
        $.ajax({
            url: '',
            type: 'POST',
            data: formData,
            success: function (response) {
                $('#cover').css('display', 'none');
                console.log(response)
                if(response.error){
                    $.each(response.errors, function(name, error){
                        error = '<small class="text-muted error">' + error + '</small>'
                        $form.find('[name=' + name + ']').after(error);
                    })
                }
                else{
                    document.getElementById('recognized').innerHTML = "Recognized : " + response.recognized;
              	    
                    document.getElementById('probability').innerHTML = "Probability : " +response.probability;
                    document.getElementById('resultpart').classList.add("card-panel");
document.getElementById('resultpart').classList.add("blue");

                    var rawResponse = response.image; // truncated for example                 
                    var outputImg = document.getElementById('image');
                    outputImg.src = "data:image/png;base64,"+ rawResponse;

                }
            },
            cache: false,
            contentType: false,
            processData: false
        });
    });
</script>

</html>